version: '3.4'

x-build:
  &build
  context: ./
  dockerfile: ./docker/ruby-with-neologd/Dockerfile

services:
  latest:
    image: jksy/ruby-with-neologd:2.6.5-latest
    build:
      *build

  build-date:
    image: jksy/ruby-with-neologd:2.6.5-${BUILD_DATE}
    build:
      *build
